### ISSUE TITLE
from yolov8 import YOLOv8

### ISSUE THREAD

**Issue by J1EXA** [ibaiGorordo/ONNX-YOLOv8-Object-Detection#17]
`from yolov8 import YOLOv8`
What is this?
pip install yolov8
gives me  yolov8.py > _init_.py >__version__ = "0.0.2"

**Comment by ibaiGorordo** [comment]
It is just the folder inside this repository. if you run the code from inside the main folder of this repository it should run without issues:
https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection#installation
