### ISSUE TITLE
Overred error while running ???

### ISSUE THREAD

**Issue by timbuktu031** [ibaiGorordo/ONNX-YOLOv8-Object-Detection#2]
[http @ 00000155d6b232c0] Stream ends prematurely at 126764, should be 18446744073709551615
[mjpeg @ 00000155d6b44840] overread 5

------------------------

When I run it, it works for a while, then the program terminates with this error.

**Comment by ibaiGorordo** [comment]
That is probably an issue with the cap_from_youtube library (https://github.com/ibaiGorordo/cap_from_youtube). Closing this issue since it is not related with the repository
