### ISSUE TITLE
How to do detection in only selected classes , not all my classes

### ISSUE THREAD

**Issue by VYRION-Ai** [ibaiGorordo/ONNX-YOLOv8-Object-Detection#7]
How to do detection in only selected classes , not all my classes

**Comment by Tamminhdiep97** [comment]
I do a little trick like this in **yolov8/utils.py**
![image](https://user-images.githubusercontent.com/39164631/222129717-55cc3674-7c78-4e5e-8bbc-46a0e35f8a05.png)
cls_id = 0 is for human only

well, i don't really know anyway other than this, i know that this trick is only work on display on image, the network will still detecting all the classes, so anyone know the proper answer please delight us.

**Comment by VYRION-Ai** [comment]
@Tamminhdiep97 as you said , just doing filter like this 
at top 
`class_filter=[0,1,2,3,4,5,6,7]`


```
`    for box, score, class_id in zip(boxes, scores, class_ids):

      if class_id in class_filter:`
```

**Comment by ibaiGorordo** [comment]
Thanks!
